steps:
  # Build and Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/active-michigan-api', './backend/active-michigan-api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/active-michigan-api']

  # Build and Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/active-michigan-frontend', './frontend/active-michigan-angular']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/active-michigan-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'active-michigan-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/active-michigan-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'active-michigan-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/active-michigan-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/active-michigan-api'
  - 'gcr.io/$PROJECT_ID/active-michigan-frontend'
